name: Build Windows 7 Compatible Executable

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Чтение кода
      uses: actions/checkout@v4

    - name: Настройка Python 3.8 (для Windows 7)
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Установка PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.13.0

    - name: Сборка EXE
      run: |
        pyinstaller --onefile --noconsole --name "SchoolTestApp" app.py

    - name: Сохранение приложения
      uses: actions/upload-artifact@v4
      with:
        name: SchoolTestApp-Win7
        path: dist/SchoolTestApp.exe
